import { CyclePhase } from '@/types';

export type ArticleCategory = 'nutrition' | 'movement' | 'recovery' | 'hormones' | 'skin' | 'mental';

export interface Article {
  id: string;
  titleKey: string;
  summaryKey: string;
  bodyKey: string;
  phase: CyclePhase | 'all';
  category: ArticleCategory;
  icon: string;
  readMinutes: number;
  isPremium: boolean;
}

export const ARTICLES: Article[] = [
  // === MENSTRUAL PHASE ===
  {
    id: 'art_menstrual_iron',
    titleKey: 'articles.menstrualIronTitle',
    summaryKey: 'articles.menstrualIronSummary',
    bodyKey: 'articles.menstrualIronBody',
    phase: 'menstrual',
    category: 'nutrition',
    icon: 'Apple',
    readMinutes: 3,
    isPremium: false,
  },
  {
    id: 'art_menstrual_rest',
    titleKey: 'articles.menstrualRestTitle',
    summaryKey: 'articles.menstrualRestSummary',
    bodyKey: 'articles.menstrualRestBody',
    phase: 'menstrual',
    category: 'recovery',
    icon: 'Moon',
    readMinutes: 3,
    isPremium: false,
  },
  {
    id: 'art_menstrual_gentle',
    titleKey: 'articles.menstrualGentleTitle',
    summaryKey: 'articles.menstrualGentleSummary',
    bodyKey: 'articles.menstrualGentleBody',
    phase: 'menstrual',
    category: 'movement',
    icon: 'Flower2',
    readMinutes: 2,
    isPremium: false,
  },
  {
    id: 'art_menstrual_skin',
    titleKey: 'articles.menstrualSkinTitle',
    summaryKey: 'articles.menstrualSkinSummary',
    bodyKey: 'articles.menstrualSkinBody',
    phase: 'menstrual',
    category: 'skin',
    icon: 'Sparkles',
    readMinutes: 3,
    isPremium: true,
  },
  {
    id: 'art_menstrual_mood',
    titleKey: 'articles.menstrualMoodTitle',
    summaryKey: 'articles.menstrualMoodSummary',
    bodyKey: 'articles.menstrualMoodBody',
    phase: 'menstrual',
    category: 'mental',
    icon: 'Heart',
    readMinutes: 3,
    isPremium: false,
  },

  // === FOLLICULAR PHASE ===
  {
    id: 'art_follicular_energy',
    titleKey: 'articles.follicularEnergyTitle',
    summaryKey: 'articles.follicularEnergySummary',
    bodyKey: 'articles.follicularEnergyBody',
    phase: 'follicular',
    category: 'movement',
    icon: 'Zap',
    readMinutes: 3,
    isPremium: false,
  },
  {
    id: 'art_follicular_nutrition',
    titleKey: 'articles.follicularNutritionTitle',
    summaryKey: 'articles.follicularNutritionSummary',
    bodyKey: 'articles.follicularNutritionBody',
    phase: 'follicular',
    category: 'nutrition',
    icon: 'Salad',
    readMinutes: 3,
    isPremium: false,
  },
  {
    id: 'art_follicular_creativity',
    titleKey: 'articles.follicularCreativityTitle',
    summaryKey: 'articles.follicularCreativitySummary',
    bodyKey: 'articles.follicularCreativityBody',
    phase: 'follicular',
    category: 'mental',
    icon: 'Lightbulb',
    readMinutes: 2,
    isPremium: false,
  },
  {
    id: 'art_follicular_skin_glow',
    titleKey: 'articles.follicularSkinGlowTitle',
    summaryKey: 'articles.follicularSkinGlowSummary',
    bodyKey: 'articles.follicularSkinGlowBody',
    phase: 'follicular',
    category: 'skin',
    icon: 'Sun',
    readMinutes: 3,
    isPremium: true,
  },
  {
    id: 'art_follicular_social',
    titleKey: 'articles.follicularSocialTitle',
    summaryKey: 'articles.follicularSocialSummary',
    bodyKey: 'articles.follicularSocialBody',
    phase: 'follicular',
    category: 'mental',
    icon: 'Users',
    readMinutes: 2,
    isPremium: false,
  },

  // === OVULATION PHASE ===
  {
    id: 'art_ovulation_peak',
    titleKey: 'articles.ovulationPeakTitle',
    summaryKey: 'articles.ovulationPeakSummary',
    bodyKey: 'articles.ovulationPeakBody',
    phase: 'ovulation',
    category: 'movement',
    icon: 'Trophy',
    readMinutes: 3,
    isPremium: false,
  },
  {
    id: 'art_ovulation_nutrition',
    titleKey: 'articles.ovulationNutritionTitle',
    summaryKey: 'articles.ovulationNutritionSummary',
    bodyKey: 'articles.ovulationNutritionBody',
    phase: 'ovulation',
    category: 'nutrition',
    icon: 'Flame',
    readMinutes: 3,
    isPremium: false,
  },
  {
    id: 'art_ovulation_confidence',
    titleKey: 'articles.ovulationConfidenceTitle',
    summaryKey: 'articles.ovulationConfidenceSummary',
    bodyKey: 'articles.ovulationConfidenceBody',
    phase: 'ovulation',
    category: 'mental',
    icon: 'Star',
    readMinutes: 2,
    isPremium: false,
  },
  {
    id: 'art_ovulation_skin_active',
    titleKey: 'articles.ovulationSkinActiveTitle',
    summaryKey: 'articles.ovulationSkinActiveSummary',
    bodyKey: 'articles.ovulationSkinActiveBody',
    phase: 'ovulation',
    category: 'skin',
    icon: 'Sparkles',
    readMinutes: 3,
    isPremium: true,
  },
  {
    id: 'art_ovulation_hydration',
    titleKey: 'articles.ovulationHydrationTitle',
    summaryKey: 'articles.ovulationHydrationSummary',
    bodyKey: 'articles.ovulationHydrationBody',
    phase: 'ovulation',
    category: 'nutrition',
    icon: 'Droplets',
    readMinutes: 2,
    isPremium: false,
  },

  // === LUTEAL PHASE ===
  {
    id: 'art_luteal_comfort',
    titleKey: 'articles.lutealComfortTitle',
    summaryKey: 'articles.lutealComfortSummary',
    bodyKey: 'articles.lutealComfortBody',
    phase: 'luteal',
    category: 'nutrition',
    icon: 'Cookie',
    readMinutes: 3,
    isPremium: false,
  },
  {
    id: 'art_luteal_sleep',
    titleKey: 'articles.lutealSleepTitle',
    summaryKey: 'articles.lutealSleepSummary',
    bodyKey: 'articles.lutealSleepBody',
    phase: 'luteal',
    category: 'recovery',
    icon: 'Moon',
    readMinutes: 3,
    isPremium: false,
  },
  {
    id: 'art_luteal_mood',
    titleKey: 'articles.lutealMoodTitle',
    summaryKey: 'articles.lutealMoodSummary',
    bodyKey: 'articles.lutealMoodBody',
    phase: 'luteal',
    category: 'mental',
    icon: 'Brain',
    readMinutes: 3,
    isPremium: false,
  },
  {
    id: 'art_luteal_gentle_movement',
    titleKey: 'articles.lutealGentleMovementTitle',
    summaryKey: 'articles.lutealGentleMovementSummary',
    bodyKey: 'articles.lutealGentleMovementBody',
    phase: 'luteal',
    category: 'movement',
    icon: 'Flower2',
    readMinutes: 2,
    isPremium: false,
  },
  {
    id: 'art_luteal_skin_care',
    titleKey: 'articles.lutealSkinCareTitle',
    summaryKey: 'articles.lutealSkinCareSummary',
    bodyKey: 'articles.lutealSkinCareBody',
    phase: 'luteal',
    category: 'skin',
    icon: 'Shield',
    readMinutes: 3,
    isPremium: true,
  },

  // === ALL PHASES ===
  {
    id: 'art_all_hydration',
    titleKey: 'articles.allHydrationTitle',
    summaryKey: 'articles.allHydrationSummary',
    bodyKey: 'articles.allHydrationBody',
    phase: 'all',
    category: 'nutrition',
    icon: 'Droplets',
    readMinutes: 3,
    isPremium: false,
  },
  {
    id: 'art_all_sleep_hygiene',
    titleKey: 'articles.allSleepHygieneTitle',
    summaryKey: 'articles.allSleepHygieneSummary',
    bodyKey: 'articles.allSleepHygieneBody',
    phase: 'all',
    category: 'recovery',
    icon: 'BedDouble',
    readMinutes: 3,
    isPremium: false,
  },
  {
    id: 'art_all_stress_breathing',
    titleKey: 'articles.allStressBreathingTitle',
    summaryKey: 'articles.allStressBreathingSummary',
    bodyKey: 'articles.allStressBreathingBody',
    phase: 'all',
    category: 'mental',
    icon: 'Wind',
    readMinutes: 2,
    isPremium: false,
  },
  {
    id: 'art_all_anti_inflammatory',
    titleKey: 'articles.allAntiInflammatoryTitle',
    summaryKey: 'articles.allAntiInflammatorySummary',
    bodyKey: 'articles.allAntiInflammatoryBody',
    phase: 'all',
    category: 'nutrition',
    icon: 'Leaf',
    readMinutes: 4,
    isPremium: true,
  },
  {
    id: 'art_all_cycle_syncing',
    titleKey: 'articles.allCycleSyncingTitle',
    summaryKey: 'articles.allCycleSyncingSummary',
    bodyKey: 'articles.allCycleSyncingBody',
    phase: 'all',
    category: 'hormones',
    icon: 'RefreshCw',
    readMinutes: 4,
    isPremium: false,
  },
];

export const ARTICLE_CATEGORIES: { key: ArticleCategory; icon: string; labelKey: string }[] = [
  { key: 'nutrition', icon: 'Apple', labelKey: 'articles.categoryNutrition' },
  { key: 'movement', icon: 'Dumbbell', labelKey: 'articles.categoryMovement' },
  { key: 'recovery', icon: 'Moon', labelKey: 'articles.categoryRecovery' },
  { key: 'hormones', icon: 'RefreshCw', labelKey: 'articles.categoryHormones' },
  { key: 'skin', icon: 'Sparkles', labelKey: 'articles.categorySkin' },
  { key: 'mental', icon: 'Brain', labelKey: 'articles.categoryMental' },
];
